# Generated by Django 5.0.1 on 2024-05-17 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiers1',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='Archivetc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL)),
                ('matiers1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='TC.matiers1')),
            ],
        ),
    ]
