# Generated by Django 5.0.1 on 2024-05-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0002_alter_matiers1_options_archivetc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivetc',
            name='created_by',
        ),
    ]
